image:
  repository: ghcr.io/maintainerr/maintainerr
  tag: 2.26.0

route:
  enabled: true
  hostnames:
    - maintainerr.mobrockers.com
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway
      sectionName: web-https
