seerr:
  image:
    repository: ghcr.io/seerr-team/seerr
    tag: v3.1.0

route:
  enabled: true
  hostnames:
  - seerr.mobrockers.com
  - overseerr.mobrockers.com
  parentRefs:
  - name: private
    namespace: envoy-gateway
    sectionName: web-https
  - name: public
    namespace: envoy-gateway
    sectionName: web-https
