opentherm-monitor:
  route:
    enabled: true
    hostnames:
      - opentherm-monitor.mobrockers.com
    parentRefs:
      - name: envoy-gateway
        namespace: envoy-gateway
        sectionName: web-https
