gateway-helm:
  deployment:
    envoyGateway:
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
    replicas: 2

  config:
    envoyGateway:
      provider:
        type: Kubernetes
        kubernetes:
          deploy:
            type: GatewayNamespace
      logging:
        level:
          default: info # debug/info/error/warn

certificates:
  - name: wildcard-mobrockers-com
    dnsNames:
      - 'mobrockers.com'
      - '*.mobrockers.com'
  - name: wildcard-s3-mobrockers-com
    dnsNames:
      - 's3.mobrockers.com'
      - '*.s3.mobrockers.com'

privateGateway:
  enabled: true
  loadBalancerIP: 10.0.103.21

publicGateway:
  enabled: false
  loadBalancerIP: 10.0.103.22
  publicIP: 87.212.115.7
