records:
- name: vpn
  ip: 87.212.115.7
- name: k8s
  ip: 10.0.102.10

routes:
- name: robin
  clientID: 9XuNncO5i9nKVPbjpgjiadXFoEMLUOKyvJXLELj9
  clientSecretSealed: AgDHO21uxHG41WvZY5oaN7Z2rHgsetWYSvoBB8JpOseBcDFE0lNFRYDZoMf69aJDdtFLTvcWRjlC5QiKP9dEB8QzpbPLOG27rmWc8m+hIw2hizm8soX1q9LxLX4uvz4/Bk8v1aiBR+awaU0gTXbybZcenyfZNnJNjiWCM35IH1ypnsQJKkmZnGA4bb3dQJwngz7NpmuJK/yovWXSjy0B+3O7pF05Y4U2ITttqOnmy9FPjO77uR/pblwes8Hp0+ZZ9gKEUat8fXpxMiwLaP1hKOCUFCkxDCAM0khOUAwIbQNl9zJFnbCX3F6POPpVtLf00KN7jyK9/woT40QmcdQiQuuASFVEOZz4SvojKh5MyAKb9Dezdx6T1WMPc4OnR/uAWEpqrSQcsvAavoH97gVYCnEHOYyLAKnABktJwmu/EpAh5dhn2vZsbKfrYwE17QNnZmxRsM2EASXMjhQGzbp2t7E0T2fII8Cb8l9+7BIXaSZePjweNVyCxGWMN5oJhAzZblupIAnRA2qzaCXVio+rrZFpDb//pD/jTW4UKw/ZUmU23/z0IvO4R5fQosuiYiblRpuESHDxkArULKbe8eSvJnbxbmE4YqNjU1cefzbHaPCwLpGaFb/XXUS8XQAsuGA+knBBoEStuAVpWUOC3Fy9PYcXLsZs5Kc8mZvyzrW2DjDAqgtlIHKga0+dyAe6lHUz99vvo54d0enS089BX9ZoH7iv5+Ah9OQGeqYK0+4Jxv4HalkQkk66usroXIttTCLK6iWYZKotmEt42s6xxL/53NyLkVBafd/Zq7WwDlYF1Kb/2SpBIkR94IJezch9hmdRC3aDbiBbCgDpA5QC1etCo5u/gvvtJnTiQjob2/h40wlgVA==
  ip: 10.0.30.45
  port: 80
- name: ava
  clientID: EyeqaUPUJg2t85mY3FBy7sPRACU0MPVpe1sVAEpF
  clientSecretSealed: AgArnNLK4T2TEZm60HYcvvzlG8AMUDT/02aI5RuIg1FdPAdBF6MiNGCGAhrqw7EVhL6aXshz1HnDMTh8tkgadDL8Bwcc3JVhUgFByZTWPDu5HJAeeHsMv5yfcq4bxPF6ECk6HbmzJ4vPg5C18/lWHbVk5m7MKiZwcTxksyi/FFPJRnpt2oh1RTc342raknqr4fqee8Ny62Zdfcnxi4tHJqefyFhysy+FMgKJFfoHWgrmBNzWUrY2yZO/RVswfJF+eHHJKgvq3ESE2Snll4OtKtIalOIZ0HTLEHq3iJQiOm7H3OGVTafW6vzuSkBf4Yjs8e/Uo/7MsAGyq+h1ORJYgXQntXJ5zULLsK5CtIGFUFGq6lOzIjXEcGtYy0BBwmlc6a5tzIcwe0n/mRy5aAbwjo8wcPVl3X3xvDnXP6hcJAQJLmu4CpaBTNRKqK7kfxV5at39zlWAn5ExjeBpG45c+NY5xM5/ZH63ATVLUPX7mXZNEZLZcLT7z6lBzdc1Gaigg8IcAOHCT/k0d+NBnAPWEoafbzrBjlJrpcY7Ym29vRXEfNPsx33iQvpJNyY8r7oKO+v8rONiAWYCE3N9psO+bqq6eidzU06YFLYqUCez5FVQsKn3rdKyAjhcehmlDk1LsNJknYWBOVIx21EaF8JNh76xz+GS3qO90b3i9MsB8UF4tuFqnGIj7dCozraewFJl8UzPGIAG2+pC3Z77XtE6J8QJ0QOD66+s7fJp/Fgy6ldZC71vcCeqNDOTdh91rpeZ397wsbyeep78p+ko4cEn2RW0JjUYjUk4ObcGpEziWN1t1YBATBuU5nP4CcFq1soIuBuLQPrMQxEhrFPwK5jN+1ms51KhJr+6GfccYtAnVVqnwQ==
  ip: 10.0.30.36
  port: 80
