records:
- name: vpn
  ip: 87.212.115.7
- name: k8s
  ip: 10.0.102.10

routes:
- name: robin
  public: true
  private: true
  clientID: 9XuNncO5i9nKVPbjpgjiadXFoEMLUOKyvJXLELj9
  clientSecretSealed: AgDHO21uxHG41WvZY5oaN7Z2rHgsetWYSvoBB8JpOseBcDFE0lNFRYDZoMf69aJDdtFLTvcWRjlC5QiKP9dEB8QzpbPLOG27rmWc8m+hIw2hizm8soX1q9LxLX4uvz4/Bk8v1aiBR+awaU0gTXbybZcenyfZNnJNjiWCM35IH1ypnsQJKkmZnGA4bb3dQJwngz7NpmuJK/yovWXSjy0B+3O7pF05Y4U2ITttqOnmy9FPjO77uR/pblwes8Hp0+ZZ9gKEUat8fXpxMiwLaP1hKOCUFCkxDCAM0khOUAwIbQNl9zJFnbCX3F6POPpVtLf00KN7jyK9/woT40QmcdQiQuuASFVEOZz4SvojKh5MyAKb9Dezdx6T1WMPc4OnR/uAWEpqrSQcsvAavoH97gVYCnEHOYyLAKnABktJwmu/EpAh5dhn2vZsbKfrYwE17QNnZmxRsM2EASXMjhQGzbp2t7E0T2fII8Cb8l9+7BIXaSZePjweNVyCxGWMN5oJhAzZblupIAnRA2qzaCXVio+rrZFpDb//pD/jTW4UKw/ZUmU23/z0IvO4R5fQosuiYiblRpuESHDxkArULKbe8eSvJnbxbmE4YqNjU1cefzbHaPCwLpGaFb/XXUS8XQAsuGA+knBBoEStuAVpWUOC3Fy9PYcXLsZs5Kc8mZvyzrW2DjDAqgtlIHKga0+dyAe6lHUz99vvo54d0enS089BX9ZoH7iv5+Ah9OQGeqYK0+4Jxv4HalkQkk66usroXIttTCLK6iWYZKotmEt42s6xxL/53NyLkVBafd/Zq7WwDlYF1Kb/2SpBIkR94IJezch9hmdRC3aDbiBbCgDpA5QC1etCo5u/gvvtJnTiQjob2/h40wlgVA==
  ip: 10.0.30.45
  port: 80
- name: ava
  public: true
  private: true
  clientID: LBvhblOnxHQBV0XJianl220f7bGAB8n4PqDQLDba
  clientSecretSealed: AgBq5eyU21b5vr/N19HXOqP5J6qSSApVXCEuR1ihto8Lw52f90/0F4RVbCMrtKMeuQOa+ErFMBPcm1SlBV+ZGypR93CVoVgh17lQ/DRMr2wKATDvZFNu+xtM0ko/FN/8o0NlUKH6x4od/AMCxp0+gZwg4jqaWqfIvdSBLe4tKEmXNcywpzCbPqnC68a0QkMEbNVzNJzz4+dBjHkWUiUb+wXchiMPnqD4TEJmE2/HmujszyVqIzPkE+mpfyc6rAd9+FFtZU9o0rdPKjDaJatjHRDg6SZsBN2S+0uqDJfeCdOp2emRdxQaaIlilsvAGLKm7sSN3mggRTcEmuXS7omho4k8tMf6SbcgZwTfktikkK7K6nBWPOryz0TkxVQXJqudVS8Syk33LN9bcknvYszMhVm0djpTjfwlqdodeYpnOn6gdOmAESiPwxvuj2lDTU6Bm53+wfOg34ldI/TsT3npQ7lj3mFaOrG50bMIXeOGXUAs2HGcLDdhlFA0MMDx8YqZDy6SI19HmNKfQNyLC0jCOy5+rubKyVf2zqt4yteyl0KhdsaxNqI10Vdhtm0CqyxhIa6El2XDyvov0Shy/578erbL0diS03oEPKWBj2m03D5CY6+kLwbdPzbP0UoJlSR98LWeAykEX5tkMQwYoLJvm8wlFCnGnn2/0WHhFhW3C9Y8bYdaO8R75QyxMIJaZEXQwn+vcH4fLP7gVieU/ix6yuP4wG6N+oFQKFjeAoFVFVKzAcvEK/E5AgrsB6UlufOXseqDfuWMTYihQ2NDFim1s+uki2n97tc49ybTEGAlZxVm8MycYDePGVc7dgNZ2FQu3v0QRS0oO6p1v9Y6OnejkxvNzjVjcUWQ7O/Rwot44gArBA==
  ip: 10.0.30.36
  port: 80
