apiVersion: v2
name: prometheus
version: 1.0.0

dependencies:
  - name: prometheus-operator-crds
    version: 25.0.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: kube-prometheus-stack
    version: 80.2.2
    repository: https://prometheus-community.github.io/helm-charts
