apiVersion: v2
name: prometheus
version: 1.0.0

dependencies:
  - name: prometheus-operator-crds
    version: 27.0.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: kube-prometheus-stack
    version: 81.6.7
    repository: https://prometheus-community.github.io/helm-charts
